[workspace]
resolver = "2"

members = [
    "src/intershare_sdk",
    "src/intershare_sdk_ffi",
    "src/protocol"
]

exclude = [
    "src/intershare_windows"
]

[workspace.lints.clippy]
needless_return = "allow"