[package]
name = "intershare_sdk_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[lints]
workspace = true

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
async-std = "1.12.0"
intershare_sdk = { package = "intershare_sdk", path = "../intershare_sdk" }
uniffi = { git = "https://github.com/julian-baumann/uniffi-rs", rev = "9bbf2d2", features = ["cli", "tokio", "default"] }
thiserror = "1.0"
tokio = { version = "1.35.1", features = ["sync"] }

[build-dependencies]
uniffi = { git = "https://github.com/julian-baumann/uniffi-rs", rev = "9bbf2d2",  features = ["build"] }
